# Generated by Django 3.2 on 2023-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='max_users',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount_percentage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='valid_for_first_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UsedCode',
        ),
    ]
