# Generated by Django 3.2 on 2023-02-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='shoe_size',
        ),
    ]
