# Generated by Django 3.2 on 2022-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221220_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
