# Generated by Django 3.2 on 2023-02-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_shoe_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shoe_sizes',
        ),
    ]
