# Generated by Django 3.2 on 2023-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_shoe_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_words',
            field=models.TextField(blank=True),
        ),
    ]
