# Generated by Django 3.2 on 2023-02-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
